spring.application.name=be-springboot-lum
server.port=8686

# PostgreSQL (default port 5432)
spring.datasource.url=jdbc:postgresql://localhost:5433/lum_trace_db
spring.datasource.username=postgres
spring.datasource.password=demo1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# API prefix
api.prefix=/api/v1

# JWT
jwt.secret=edafc99abc17f95b1e45bd286f8b9da15854996bc993d3f826dff842f2dfb9c4ce9027b3e3b9b0eb4a227382617a7128ee0b176b7e9d71aadc627ad65f73f522
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=1209600000

# Mail (Gmail SMTP - update credentials)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=demotestmot@gmail.com
spring.mail.password=kzqa lepy hpee miyz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend URL (for password reset link)
app.frontend-url=http://localhost:3000

# Cookie: false khi dev (HTTP), true khi production (HTTPS)
app.cookie.secure=false

# Google OAuth2
google.oauth2.client-id=999032647976-ttau163hg8dr103nqegv56vkksg6q6cg.apps.googleusercontent.com
google.oauth2.client-secret=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
google.oauth2.callback-url=http://localhost:8686/api/v1/auth/google/callback
# google.oauth2.callback-url=https://josie-juxtapositional-rebbecca.ngrok-free.dev/api/v1/auth/google/callback
google.oauth2.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
google.oauth2.token-uri=https://oauth2.googleapis.com/token
google.oauth2.userinfo-uri=https://www.googleapis.com/oauth2/v3/userinfo

# Async
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=100